# 20160044 Shin Dong-Ha Assignment10
# Github Link : https://github.com/sinwindis/Assignment10

Importing Necessary Libraries

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
from scipy.linalg import lstsq

provided code

In [2]:
file_data_train = "mnist_train.csv"
file_data_test  = "mnist_test.csv"

h_data_train    = open(file_data_train, "r")
h_data_test     = open(file_data_test, "r")

data_train      = h_data_train.readlines()
data_test       = h_data_test.readlines()

h_data_train.close()
h_data_test.close()

size_row    = 28    # height of the image
size_col    = 28    # width of the image

num_train   = len(data_train)   # number of training images
num_test    = len(data_test)    # number of testing images

#
# normalize the values of the input data to be [0, 1]
#
def normalize(data):

    data_normalized = (data - min(data)) / (max(data) - min(data))

    return(data_normalized)

#
# example of distance function between two vectors x and y
#
def distance(x, y):

    d = (x - y) ** 2
    s = np.sum(d)
    # r = np.sqrt(s)

    return(s)

#
# make a matrix each column of which represents an images in a vector form 
#
list_image_train    = np.empty((size_row * size_col, num_train), dtype=float)
list_label_train    = np.empty(num_train, dtype=int)

list_image_test     = np.empty((size_row * size_col, num_test), dtype=float)
list_label_test     = np.empty(num_test, dtype=int)

count = 0

for line in data_train:

    line_data   = line.split(',')
    label       = line_data[0]
    im_vector   = np.asfarray(line_data[1:])
    im_vector   = normalize(im_vector)

    list_label_train[count]     = label
    list_image_train[:, count]  = im_vector    

    count += 1

count = 0

for line in data_test:

    line_data   = line.split(',')
    label       = line_data[0]
    im_vector   = np.asfarray(line_data[1:])
    im_vector   = normalize(im_vector)

    list_label_test[count]      = label
    list_image_test[:, count]   = im_vector    

    count += 1


FUCNTION DEFINITION: sign(x)

In [3]:
def sign(x):
    if x >= 0:
        return 1
    else:
        return -1

DEFINE FUNCTION: generateRandomVector(sigma, precision, randomvector)

gets precision number of 784-sized vector whose element value is random value based on normal distribution

In [4]:
def generateRandomVector(sigma, precision, randomvector):

    size = (size_row*size_col)
    
    for i in range(precision):
        randomvector.append(np.random.normal(0, sigma, size))

DEFINE FUNCTION: fi(i, x)
    
$$returns:f_i(x) = r_i^Tx$$

In [5]:
def fi(i, x):
    score = float()
    
    for j in range(size_row*size_col):
        score += r[i][j]*x[j]

    return score

DEFINE FUNCTION: makeXhat


Generated Matrix
$$AX = B$$
$$A = [x_1, x_2, \dots, x_{p}]$$
$$X^T = [\theta_1, \theta_2, \dots, \theta_{p}]$$
$$B = isThatNum$$
$$\hat{X} = (A^TA)^{-1}A^TB$$

Returned Value
$$\hat{X}$$

In [6]:
def makeXhat(makeXhat_precision, classifiNum):
    
    A = np.empty((num_train, makeXhat_precision), dtype=float)
    B = np.empty((num_train), dtype=float)
    
    for i in range(num_train):
        for j in range(makeXhat_precision):
            A[i][j] = fi(j, list_image_train[:, i])
        
        
    for i in range(num_train):
        if list_label_train[i] == classifiNum:
            B[i] = 1
        else:
            B[i] = -1
    
    #Xhat = np.matmul(np.matmul(np.transpose(A), inv(np.matmul(A, np.transpose(A)))), B)
    
    return lstsq(A, B)

DEFINE FUNCTION: classifier
$$classifier(precision, imageMatrix)$$
$$return: \theta_1f_1(imageMatrix) + \theta_2f_2(imageMatrix) + \dots + \theta_{precision}f_{precision}(imageMatrix)$$

In [7]:
def classifier(precision, testee, xhat):

    resSum = float()
    
    for i in range(precision):
        resSum += fi(i, testee)*xhat[i]
        
    return resSum

DEFINE FUNCTION: showResult(precision)

Makes Xhat, Distributes images, Shows average images

In [83]:
def showResult(p):

    
    confusionMatrix = list()
    
    #result = [answer, classifiResult]
    result = np.empty((num_test, 2), dtype=int)
    resultMatrix = np.zeros((10, 10), dtype=int)
    classresult = float()

    print("precision = ", p)
    
    for i in range(num_test):
        scoreTemp = classifier(p, list_image_test[:, i], thetaMatrix[p*10 - 10 + 9][0])
        result[i, 1] = 9
        result[i, 0] = list_label_test[i]
        for j in range(9):
            classresult = classifier(p, list_image_test[:, i], thetaMatrix[p*10 - 10 + j][0])
            if classresult > scoreTemp:
                result[i, 1] = j
                
    for i in range(num_test):
        resultMatrix[result[i, 0], result[i,1]] += 1
        
    score_precision = 
    
    print(resultMatrix)

In [27]:
def generateXhat(p):
    for i in range(10):
        thetaMatrix.append(makeXhat(p, i))

In [34]:
sigma = 1
thetaMatrix = list()
precision = 10
r = list()
generateRandomVector(sigma, precision, r)    

In [35]:
generateXhat(1)

In [36]:
generateXhat(2)

In [37]:
generateXhat(3)

In [38]:
generateXhat(4)

In [39]:
generateXhat(5)

In [40]:
generateXhat(6)

In [41]:
generateXhat(7)

In [42]:
generateXhat(8)

In [43]:
generateXhat(9)

In [44]:
generateXhat(10)

In [90]:
scoreList = list()

In [78]:
showResult(1)

precision =  1
[[  0   0   0   0   0   0   0   0 620 360]
 [  0   0   0   0   0   0   0   0 294 841]
 [  0   0   0   0   0   0   0   0 190 842]
 [  0   0   0   0   0   0   0   0  80 930]
 [  0   0   0   0   0   0   0   0  81 901]
 [  0   0   0   0   0   0   0   0 103 789]
 [  0   0   0   0   0   0   0   0 190 768]
 [  0   0   0   0   0   0   0   0 113 915]
 [  0   0   0   0   0   0   0   0  62 912]
 [  0   0   0   0   0   0   0   0  21 988]]


In [84]:
showResult(2)

precision =  2
[[ 25   0   0   0 428  77  63  23 223 141]
 [  1   0   0   0   8   3   5   5 815 298]
 [ 12   0   0   0  39   4  10   5 644 318]
 [  7   0   0   0  32   6   5   1 316 643]
 [ 25   0   0   0  95   2   4   2 214 640]
 [  9   0   0   0  33   6   7   2 304 531]
 [ 20   0   0   0 108  15  22   8 341 444]
 [ 10   0   0   0  27   1   4   4 614 368]
 [  4   0   0   0  12   3   3   1 453 498]
 [ 13   0   0   0  31   1   1   0 162 801]]


In [85]:
showResult(3)

precision =  3
[[ 12   0   0  16 237  14 393  76 164  68]
 [  0   0   3  38   4   0 247 134 593 116]
 [  3   0   0  35  17   2 218 107 513 137]
 [  7   0   2  57  10   0 334  72 204 324]
 [ 18   0   0  46  82   0 135  35 259 407]
 [  5   0   0  65  17   2 227  38 273 265]
 [ 13   0   1  52  49   6 362 107 191 177]
 [  0   0   1  15  23   1  59  35 681 213]
 [  2   0   0  21  10   0  95  16 543 287]
 [  4   0   1  43  22   0 119  14 203 603]]


In [86]:
showResult(4)

precision =  4
[[ 20   0   0  24 154  37 391  62 241  51]
 [  0 154   7   5  10   0 187 195 443 134]
 [  5  11   3  40  17   3 208 100 554  91]
 [  6  13   0 101  18   0 315  62 281 214]
 [ 21  40   0  30 128   3 106  33 265 356]
 [  7  14   1  72  36   0 230  33 301 198]
 [  8   4   0  63  40   5 392 103 240 103]
 [  1  21   0  10  57   2  47  29 634 227]
 [  3  36   3  39  20   1  75  31 540 226]
 [  7  28   1  36  27   0  91  11 227 581]]


In [87]:
showResult(5)

precision =  5
[[  5   0   0  10  62  20 322  59 485  17]
 [  0 139  45   5  13   0 173 170 450 140]
 [  4   8  30  42  17   1 171  83 568 108]
 [  8   0   2  82  32   5 264  86 374 157]
 [ 21  15   2  21 154   3 112  49 312 293]
 [  5   3   0  61  40   6 208  37 386 146]
 [  4   2   4  63  28   8 335  99 343  72]
 [  4  11  11  13  61   4  38  34 683 169]
 [  3  23   9  17  30   2  78  31 604 177]
 [ 10  19   2  30  57   6  83  12 255 535]]


In [88]:
showResult(6)

precision =  6
[[  8   0   0  19  54  27 233 121 499  19]
 [  0  32  18   8   8   0 211 113 715  30]
 [  3   2   8  39  11   1 141  98 640  89]
 [ 12   2   1 106  19   9 201 209 295 156]
 [ 12   5   0  41  98   6  77 155 275 313]
 [  2   1   0  88  24   8 138 120 350 161]
 [  1   1   1  26  14   2 253  56 580  24]
 [  2   4   7  14  32   0  30 243 505 191]
 [  6   9   3  28  16   3  93  67 618 131]
 [  7   2   1  42  35   6  39  99 193 585]]


In [89]:
showResult(7)

precision =  7
[[  1   0   0   7  53  18 178  55 658  10]
 [  0  65   8  11   6   0 252 179 583  31]
 [  5   0  18  17  12   1 109  67 762  41]
 [  6   1   2 134  19   7 133 334 243 131]
 [  9   7   2  43 134   4  76 123 302 282]
 [  6   0   4  90  26   3 119 153 357 134]
 [  1   0   4  14   5   1 223  24 677   9]
 [  1   7  11  20  10   1  22 394 426 136]
 [  2   1   8  30  22   4  91  65 671  80]
 [  5   3   3  73  33   2  29  94 204 563]]


In [91]:
showResult(8)

precision =  8
[[  1   0   1   8  46  16 160  67 673   8]
 [  0   7   2 101   0   0  89  90 838   8]
 [  4   0   7  40   7   2  78  55 812  27]
 [  3   7   2 159   7   7  92 246 422  65]
 [  5   4   4  63 135   5 124 131 253 258]
 [  1   0   2 101  38   4 126 143 361 116]
 [  1   0   5  12   5   1 304  43 581   6]
 [  1   3   4  31  13   0  21 389 453 113]
 [  1   4  12  47  13   7  45  52 743  50]
 [  2   3   5  94  32   1  56 100 188 528]]


In [92]:
showResult(9)

precision =  9
[[  5   0   2   5  32  21 173 103 634   5]
 [  0   9  10  71   5   5  74 142 816   3]
 [  2   0  11  36  21   3 111 100 726  22]
 [  0   5   2 109  10  39  72 241 482  50]
 [  2   0   0  30 276   2 144 195 158 175]
 [  4   0   1  70  31  29 100 146 422  89]
 [  0   0   3  10  16   3 334  57 529   6]
 [  0   4   4  31  19   2  19 466 383 100]
 [  1   4   5  30  25   7  33  41 791  37]
 [  3   4   3  66 135   7  55 129 174 433]]


In [93]:
showResult(10)

precision =  10
[[  9   1   2   7  15  24 136  91 694   1]
 [  0  19   5  60   3  10  16 118 903   1]
 [  3   1  11  27  29   3 119  92 727  20]
 [  3  10   2 104   9  41  76 249 469  47]
 [ 14   5   1  14 322   6 163 185 135 137]
 [ 19   3   0  52  20  32  77 143 454  92]
 [  4   1   6   9  14   2 354  55 506   7]
 [  1   5   6  26  43   4  17 438 411  77]
 [  1   6  11  28  13   8  31  43 803  30]
 [ 10  10   2  54 160   8  59 136 180 390]]
